import json
from datetime import datetime


class FileHeader:
    default_date_format = "%d%m%Y"
    default_datetime_format = "%d%m%Y %H%M%S"
    default_time_format = "%H%M%S"

    def __init__(self, data):
        self.data = data
        self.attributes = {
            'bank_code': {
                'type': 'int',
                'length': 3,
                'default': 341,
                'pad_content': 0,
                'pad_direction': 'left',
                'required': True,
                'start': 0,
                'end': 3,
            },
            'lot_code': {
                'type': 'int',
                'length': 4,
                'default': 0000,
                'pad_content': 0,
                'pad_direction': 'left',
                'required': False,
                'start': 3,
                'end': 7,
            },
            'register_type': {
                'type': 'int',
                'length': 1,
                'default': 0,
                'pad_content': 0,
                'pad_direction': 'left',
                'required': True,
                'start': 7,
                'end': 8,
            },
            'register_type_whites': {
                'type': 'string',
                'length': 6,
                'default': '',
                'pad_content': ' ',
                'pad_direction': 'left',
                'required': False,
                'start': 8,
                'end': 14,
            },
            'file_layout': {
                'type': 'int',
                'length': 3,
                'default': '081',
                'pad_content': 0,
                'pad_direction': 'left',
                'required': False,
                'start': 14,
                'end': 17,
            },
            'company_description': {
                'type': 'int',
                'length': 1,
                'default': 2,
                'pad_content': 0,
                'pad_direction': 'left',
                'required': False,
                'start': 17,
                'end': 18,
            },
            'inscription_number': {
                'type': 'int',
                'length': 14,
                'default': '',
                'pad_content': 0,
                'pad_direction': 'left',
                'required': True,
                'start': 18,
                'end': 32,
            },
            'inscription_number_whites': {
                'type': 'string',
                'length': 20,
                'default': '',
                'pad_content': ' ',
                'pad_direction': 'left',
                'required': False,
                'start': 32,
                'end': 52,
            },
            'agency': {
                'type': 'int',
                'length': 5,
                'default': '',
                'pad_content': 0,
                'pad_direction': 'left',
                'required': True,
                'start': 52,
                'end': 57,
            },
            'agency_whites': {
                'type': 'string',
                'length': 1,
                'default': '',
                'pad_content': ' ',
                'pad_direction': 'left',
                'required': False,
                'start': 57,
                'end': 58,
            },
            'account': {
                'type': 'int',
                'length': 12,
                'default': '',
                'pad_content': 0,
                'pad_direction': 'left',
                'required': True,
                'start': 58,
                'end': 70,
            },
            'account_whites': {
                'type': 'string',
                'length': 1,
                'default': '',
                'pad_content': 0,
                'pad_direction': 'left',
                'required': False,
                'start': 70,
                'end': 71,
            },
            'dac': {
                'type': 'int',
                'length': 1,
                'default': 0,
                'pad_content': 0,
                'pad_direction': 'left',
                'required': True,
                'start': 71,
                'end': 72,
            },
            'company_name': {
                'type': 'string',
                'length': 40,
                'default': '',
                'pad_content': ' ',
                'pad_direction': 'right',
                'required': True,
                'start': 72,
                'end': 102,
            },
            'bank_name': {
                'type': 'string',
                'length': 30,
                'default': '',
                'pad_content': ' ',
                'pad_direction': 'right',
                'required': True,
                'start': 102,
                'end': 132,
            },
            'bank_name_whites': {
                'type': 'string',
                'length': 10,
                'default': '',
                'pad_content': 0,
                'pad_direction': 'left',
                'required': False,
                'start': 132,
                'end': 142,
            },
            'file_code': {
                'type': 'int',
                'length': 1,
                'default': 1, # 1 - Shipping / 2 - Return
                'pad_content': 0,
                'pad_direction': 'left',
                'required': True,
                'start': 142,
                'end': 143,
            },
            'generation_date': {
                'type': 'date',
                'length': 6,
                'default': datetime.strptime(datetime.utcnow(), self.default_date_format),
                'pad_content': '',
                'pad_direction': 'left',
                'required': False,
                'start': 143,
                'end': 151,
            },
            'generation_hour': {
                'type': 'date',
                'length': 6,
                'default': datetime.strptime(datetime.utcnow(), self.default_time_format),
                'pad_content': '',
                'pad_direction': 'left',
                'required': False,
                'start': 151,
                'end': 157,
            },
            'generation_zeros': {
                'type': 'int',
                'length': 9,
                'default': 0,
                'pad_content': 0,
                'pad_direction': 'left',
                'required': False,
                'start': 157,
                'end': 166,
            },
            'density_unit': {
                'type': 'int',
                'length': 5,
                'default': 0,
                'pad_content': 0,
                'pad_direction': 'left',
                'required': False,
                'start': 166,
                'end': 171,
            },
            'density_unit_whites': {
                'type': 'string',
                'length': 69,
                'default': ' ',
                'pad_content': ' ',
                'pad_direction': 'left',
                'required': False,
                'start': 171,
                'end': 240,
            },
        }
    
    def get_dict(self):
        pass
    
    def get_json(self):
        return json.dumps(self.get_dict())
