from keeper_cnab240.segment_section import SegmentSection


class SegmentZ(SegmentSection):
    def __init__(self, data=None):
        super().__init__(
            "SegmentZ",
            data,
            {
                "bank_code": {
                    "type": "int",
                    "length": 3,
                    "default": 341,
                    "pad_content": 0,
                    "pad_direction": "left",
                    "required": False,
                    "start": 0,
                    "end": 3,
                    "value": None,
                },
                "lot_code": {
                    "type": "int",
                    "length": 4,
                    "default": 0000,
                    "pad_content": 0,
                    "pad_direction": "left",
                    "required": False,
                    "start": 3,
                    "end": 7,
                    "value": None,
                },
                "register_type": {
                    "type": "int",
                    "length": 1,
                    "default": 3,
                    "pad_content": 0,
                    "pad_direction": "left",
                    "required": False,
                    "start": 7,
                    "end": 8,
                    "value": None,
                },
                "register_number": {
                    "type": "int",
                    "length": 5,
                    "default": 0,
                    "pad_content": 0,
                    "pad_direction": "left",
                    "required": True,
                    "start": 8,
                    "end": 13,
                    "value": None,
                },
                "segment_code": {
                    "type": "string",
                    "length": 1,
                    "default": "Z",
                    "pad_content": " ",
                    "pad_direction": "right",
                    "required": False,
                    "start": 13,
                    "end": 14,
                    "value": None,
                },
                "authentication": {
                    "type": "string",
                    "length": 64,
                    "default": "",
                    "pad_content": " ",
                    "pad_direction": "right",
                    "required": False,
                    "start": 14,
                    "end": 78,
                    "value": None,
                },
                "your_number": {
                    "type": "string",
                    "length": 20,
                    "default": "",
                    "pad_content": " ",
                    "pad_direction": "right",
                    "required": False,
                    "start": 78,
                    "end": 98,
                    "value": None,
                },
                "blank_1": {
                    "type": "string",
                    "length": 5,
                    "default": "",
                    "pad_content": " ",
                    "pad_direction": "right",
                    "required": False,
                    "start": 98,
                    "end": 103,
                    "value": None,
                },
                "bank_document_number": {
                    "type": "string",
                    "length": 15,
                    "default": "",
                    "pad_content": " ",
                    "pad_direction": "right",
                    "required": False,
                    "start": 103,
                    "end": 118,
                    "value": None,
                },
                "blank_2": {
                    "type": "string",
                    "length": 122,
                    "default": "",
                    "pad_content": " ",
                    "pad_direction": "right",
                    "required": False,
                    "start": 118,
                    "end": 240,
                    "value": None,
                },
            },
        )
